### PR TITLE
Made the fruit really sick

### PR DESCRIPTION
**Pull request by BTCTaras**

### CODE REVIEW

**Comment by GeorgeMcKinlay** [comment]
thx

**Comment by Codicassert** [comment]
oh its beautiful ( ͡° ͜ʖ ͡°)

**Comment by Lemmmy** [comment]
we also need :eggplant: fruit

**Comment by BTCTaras** [comment]
ill get started right away

**Comment by Lemmmy** [comment]
for the sake of following the proper skin naming scheme, please rename `sickfruit.png` to `fruit-apple.png` and make it monochrome white, and place the text on `fruit-apple-overlay.png`

eggplant should be `fruit-bananas.png`, again monochrome white, and the overlay can be coloured for the green part and the reflection (`fruit-bananas-overlay.png`) thank you

**Pull request merged**
